language: ruby
cache: bundler
env:
  global:
    - TRAVIS=true
  matrix:
    - TASK=rake
rvm:
  - 2.1.2
before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c "CREATE USER openpizza WITH PASSWORD 'password1' CREATEDB;" -U postgres
  - bundle exec rake db:setup
bundler_args: ""
script:
  - bundle exec $TASK
notifications:
  webhooks:
    - http://hubot-james.herokuapp.com/hubot/travis?room=%23kreisverkehr&type=groupchat
